//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oazachaosu.Models
{
  public partial class commonword
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Language1 { get; set; }
        public string Language2 { get; set; }
        public string Language1Comment { get; set; }
        public string Language2Comment { get; set; }
        public int State { get; set; }
    }
}
