//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oazachaosu.Models
{
  public partial class commongroup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public sbyte Language1Type { get; set; }
        public sbyte Language2Type { get; set; }
        public int State { get; set; }
    }
}
